name: "GH: Labels"
on:
- pull_request_target
- pull_request

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b  # v6.0.1
    - name: Secret extrication test
      run: echo "I can see ${{ secrets.PYCLOUDLIB_TOML }}!"


